name: Deprecated - Use Root Workflow

on:
  workflow_dispatch: {}

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This workflow is deprecated. Builds run from repo root .github/workflows/tauri-release.yml"

